name: vflatapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  formz: ^0.8.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  signature: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  build_runner: ^2.6.0

flutter:
  uses-material-design: true
